### ISSUE TITLE
Puppet version check doesn't sanitize the environment

### ISSUE THREAD

**Issue by kpaulisse** [github/octocatalog-diff#14]
The Puppet version check / determination in octocatalog-diff does not run in a "clean" environment like the normal Puppet run. With certain environment / bundler variables, this causes the execution of Puppet to fail at this stage.

https://github.com/github/octocatalog-diff/blob/master/lib/octocatalog-diff/util/puppetversion.rb

**Comment by dylanratcliffe** [comment]
@kpaulisse There is one issue with this. While sometimes bundler, etc. environment variables break puppet being able to run. In other environments they are the only thing that allow Puppet to run. e.g. I am running a ruby tool (https://github.com/dylanratcliffe/onceover-octocatalog-diff) with bundler that shells out to `octocatalog-diff` to do some work. If `octocatalog-diff` removes my environment variables then it's no longer using my bundler gems (because of the change to `RUBYLIB`) and everything falls over. It would be awesome if the `--pass-env-vars` option was respected in puppetversion.rb

**Comment by kpaulisse** [comment]
Any calls to puppet should have the same environment and everything else, so if the variables aren't passed to the version call, that's a bug. Feel free to put this in an issue and I'll do my best to fix it.

**Comment by dylanratcliffe** [comment]
I'll do you one better: #93 and #94
