### ISSUE TITLE
API

### ISSUE THREAD

**Issue by mschuchard** [github/octocatalog-diff#7]
Hi, I am the author of the leading frontend puppet testing software: Puppet-Check. I am interested in including octocatalog-diff as an optional dependency in an upcoming 1.4.0 release as another testing software to interface with. I did a cursory glance through the source code for an API, and it seems like I would need to interface with `OctocatalogDiff::CatalogDiff::Cli.cli(argv, Logger.new(STDERR), options)` and parse the output streams similar to what I have to do with Rubocop and Reek.

Is there an easier API to work with? Will there be an upcoming API?

Any suggestions or infoomation appreciated.

**Comment by kpaulisse** [comment]
You're correct that the initial release was geared toward the command line tool, mostly because that's how we use it internally at GitHub.

I could foresee that perhaps you'd want puppet-check to compile one or more catalogs using the recent facts (something currently accomplish-able with the `--catalog-only` option) because this is a pass-fail check. We currently do this as part of our CI suite, using octocatalog-diff to compile representative catalogs for one representative of each of ~50 critical roles.

Since puppet-check is a "pass/fail" type test, and the catalog difference analysis is designed more to produce output that a human reviews, I'd appreciate your thoughts on if you think there are any additional integrations between the tools that might make sense. We can certainly look at implementing an API but want to understand all of the requirements first.

**Comment by mschuchard** [comment]
Thank you for the response.

So my intention is to implement a frontend that would behave in the following way. It would trigger if all of the previous tests (whether syntax and spec or syntax) pass. At that point, octocatalog-diff would perform a test catalog compilation if the user desires. Afterwards, if information about a prior catalog compilation exists, puppetcheck would trigger octocatalog-diff to do its thing and show the differences between the current and prior catalog.

Does that make sense for my intended goal?

**Comment by kpaulisse** [comment]
@mschuchard I have started working on an API in https://github.com/github/octocatalog-diff/pull/44 for building catalogs and running the "catalog-diff" functionality.

**Comment by mschuchard** [comment]
Awesome. I will have to mention this when I present at our Puppet Camp next Thursday. Thanks!

**Comment by kpaulisse** [comment]
@mschuchard I encourage you to check out the `master` branch, which has been updated with the API code and corresponding documentation.

I'm going to close this issue for now, since it's more a general question. If you have questions or problems with any specific parts of the API, please feel free to open specific issues about those.

I look forward to seeing what you're able to build. 😸

**Comment by mschuchard** [comment]
Hopefully we see other people using this API too, such as in their CI.
